---
language: python
python: "3.6"
dist: xenial
os: linux

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - sudo apt-get update
  
install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook ansible/playbook.yml --syntax-check

notifications:
  email:
    recipients:
      - rlaehdud4992@naver.com
    on_success: always
    on_failure: always
