---
language: python
python: "3.6"
dist: xenial
os: linux

# Use the new container infrastructure
sudo: true

branches:
  only:
    - master
    - main
    # feature 서브그룹 브랜치를 정규 표현식으로 정의 ex) feature/5, feature/1
    # - /^(feature)\/\w*$/
  
# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook ansible/playbook.yml --syntax-check

  # ansible configuration
  - ansible-playbook ansible/playbook.yml

  # ansible test
  - py.test --sudo testinfra_system_daemon.py

notifications:
  email:
    recipients:
      - rlaehdud4992@naver.com
    on_success: always
    on_failure: always
